# Generated by Django 4.0.3 on 2022-03-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='created',
            new_name='date',
        ),
    ]
