# Generated by Django 4.0.3 on 2022-03-02 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_options_rename_created_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='cost_per_unit',
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(),
        ),
    ]
